# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy Node.js app to Azure Web App - chatdraftpreview

on:
  push:
    branches:
      - main
  workflow_dispatch:
env:
  # Setting an environment variable with the value of a configuration variable
  env_var: ${{ vars.ENV_CONTEXT_VAR }}

jobs:
  build:
    env:
      PUBLIC_TWITCH_OAUTH_CLIENT_ID: ${{ vars.PUBLIC_TWITCH_OAUTH_CLIENT_ID }}
      PUBLIC_TWITCH_USER_ID: ${{ vars.PUBLIC_TWITCH_USER_ID }}
      PUBLIC_TWITCH_REDIRECT_URI: ${{ vars.PUBLIC_TWITCH_REDIRECT_URI }}
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js version
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'

      - name: npm install, build, and test
        run: |
          npm install
          npm run build --if-present
          # npm run test --if-present

      - name: Zip artifact for deployment
        run: zip release.zip ./* -r

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: node-app
          path: release.zip

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: node-app

      - name: Unzip artifact for deployment
        run: unzip release.zip
        

      - name: Apply database migration and database seed
        run: |
          npm install
          npm db:migrate
          npm seed
        env: 
          SQL_DB_URI: ${{ vars.SQL_DB_URI }}

      - name: 'Deploy to Azure Web App'
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'chatdraftpreview'
          slot-name: 'Production'
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_86397FB3E65846F0B39D69C005D264A5 }}
          package: .
          clean: false
